/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package statesAndCapitals;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void Test_states_and_capitals() throws IOException, IOException {
        StatesAndCapitals sut = new StatesAndCapitals();
        sut.testStatesAndCapitals();
    }
    }

